### ISSUE TITLE
appDir parameter not used with ADD command in Dockerfile

### ISSUE THREAD

**Issue by devminded** [nebula-plugins/nebula-docker-plugin#9] opened 2017-11-01 14:59 UTC
The destination directory for the ADD command in the generated Dockerfile ignores appDir.

Gradle version: 4.0 - 4.3
JDK: 1.7 - 1.8

**Configuration**

```
nebulaDocker {
	maintainerEmail = 'yadda'
	dockerBase = 'openjdk:8-jre-alpine'
	appDir = "/opt/company/${project.applicationName}-${project.version}"
	appDirLatest = "/opt/company/app"
	dockerImage = {
		addFile 'config', '/etc/app'
		addFile 'resources', '/var/lib/app/resources'
	}
}
```

**Result**

```
FROM openjdk:8-jre-alpine
MAINTAINER yadda
ADD app-1.0.0-SNAPSHOT.tar /
RUN ln -s '/opt/company/app-1.0.0-SNAPSHOT' '/opt/company/app'
ENTRYPOINT ["/opt/company/app-1.0.0-SNAPSHOT/bin/app"]
ADD config /etc/app
ADD resources /var/lib/app/resources
```

**Expected**

```
FROM openjdk:8-jre-alpine
MAINTAINER yadda
ADD app-1.0.0-SNAPSHOT.tar /opt/company
RUN ln -s '/opt/company/app-1.0.0-SNAPSHOT' '/opt/company/app'
ENTRYPOINT ["/opt/company/app-1.0.0-SNAPSHOT/bin/app"]
ADD config /etc/app
ADD resources /var/lib/app/resources
```

**Comment by liviutudor** [comment] 2018-02-28 21:39
Verified the issue is indeed valid.

**Comment by liviutudor** [comment] 2018-02-28 23:46
@devminded  Actually looking at this again this is working as intended. The `appDir` only refers to the destination folder on the host, the file is always meant to be copied in the root folder. (Bear in mind here that the whole _nebula_ suite of plugins is very opinionated!)
However, your request is valid: what you are basically asking for is that if the `appDir` is specified then we should use the "root" of it to copy the jar to it and then the rest remains the same. The "root" bit needs a bit of thought as to what happens when you include or not the tar basename.
In your example you use `appDir="/opt/company/${project.applicationName}-${project.version}"` while `"${project.applicationName}-${project.version}"`is also used for the tarball basename which is why it seems natural to you that the resulting command should be `ADD ${project.applicationName}-${project.version}.tar /opt/company`. If we have `appDir` specified as: `appDir="/opt/company/package"` then do you expect `ADD` to be:
* `ADD ${project.applicationName}-${project.version}.tar /opt/company` *OR*
* `ADD ${project.applicationName}-${project.version}.tar /opt/company/package`
?

**Comment by liviutudor** [comment] 2018-03-01 00:04
In support of my earlier statement, here's the segment of boilerplate code we are replacing with this plugin: https://github.com/nebula-plugins/nebula-docker-plugin/wiki#boilerplate-code (from the README file)

**Comment by liviutudor** [comment] 2018-03-22 17:34
I'm going to close this for now as will not fix but happy to reopen this discussion at some point.

**Closed as completed by liviutudor** 2018-03-22 17:34 UTC
Labels: wontfix
